zstd: fix -Wdeprecated-declarations
Since 1.5.4-dev, the following is observed:

lib/zstd/zstd_decompress_module.c:80:9: error: 'ZSTD_resetDStream' is
deprecated: use ZSTD_DCtx_reset, see zstd.h for detailed instructions
[-Werror,-Wdeprecated-declarations]
        return ZSTD_resetDStream(dstream);
               ^
./include/linux/zstd_lib.h:2543:1: note: 'ZSTD_resetDStream' has been
explicitly marked deprecated here
ZSTD_DEPRECATED("use ZSTD_DCtx_reset, see zstd.h for detailed instructions")
^
./include/linux/zstd_lib.h:42:53: note: expanded from macro 'ZSTD_DEPRECATED'
                                                    ^
1 error generated.

This is due to that ZSTD_resetDStream() was marked deprecated, but no
changes in zstd_decompress_module.c followed. Who cares about the
kernel, right?
Follow the instruction from <linux/zstd_lib.h> and replace it with
ZSTD_DCtx_reset().

Fixes: 94b73f546d26 ("zstd: pull 1.5.3-dev up to 2f74507bbd0e")
Signed-off-by: Alexander Lobakin <alobakin@mailbox.org>